### ISSUE TITLE
panel sizing

### ISSUE THREAD

**Issue by KeLaiFu** [spielhuus/elektrophon#6]
maybe worth making a note about the panels being slightly taller than standard eurorack, someone may send them off for fab without realizing. Some great modules there btw, I may have a go at editing them to fit euro proportions.

**Comment by pierstu** [comment]
I started redrawing some panels, maybe it's not worth making twice the same effort. 
To the repo owner : thanks for this work and making it avalaible.

**Comment by KeLaiFu** [comment]
> I started redrawing some panels, maybe it's not worth making twice the same effort.
> To the repo owner : thanks for this work and making it avalaible.

ah, cool, I'll keep an eye on your github. Thanks!
