### ISSUE TITLE
IC sourcing

### ISSUE THREAD

**Issue by pierstu** [spielhuus/elektrophon#7]
Hello, thanks for making all this work avalaible. 

Some of these modules work around obsolete ICs, especially 3080s. I guess everyone in UE has experienced the difficulties to source some for cheap (around €8 at western brokers), which is even more ridiculous when you know that a €2 13700 is exactly a double 3080.
From a readme :

> The CA3080 is not produced anymore. But like many other chip it can be bought on the chinese market.

I dont want to debate about the IC aftermarket, but has anyone a cheap reliable source for these please? 
I know [Alfa](http://www.alfarzpp.lv/eng/sc/application.php) makes the AS3080 for a few months now, but it's still above €5 each.

Thank you, have a nice weekend

**Comment by KeLaiFu** [comment]
> CA3080

I can get the Chinese version for about 50cents, Which modules need them?

**Comment by pierstu** [comment]
About all of them. 
Can you please provide a link if any?
Did you try some? Did they happen to turn to firecrackers? 
Maybe redrawing them for 13700s will make them more sustainable in time, plus i want to get taught layout for the next lockdown

**Comment by KeLaiFu** [comment]
I found them on the Chinese amazon (of sorts) called taobao. Not sure how accessible it is outside of china, but if you need anything I am sure we could work something out. I didn't try anything myself, nothing I have put together needs them, so far.

generic cheap one
https://detail.tmall.com/item.htm?spm=a230r.1.14.16.1a7b7c91n5RbFA&id=564315790019&ns=1&abbucket=20

apparently old stock
https://item.taobao.com/item.htm?spm=a230r.1.14.90.1a7b7c91n5RbFA&id=626239264574&ns=1&abbucket=20#detail

SMD version
https://item.taobao.com/item.htm?spm=a230r.1.14.242.1a7b7c91n5RbFA&id=41293544330&ns=1&abbucket=20#detail

There's no shortage of vendors selling these, there appears to be 3 distinct brandings. One styled as the original, one with an 'i' logo on the casing and one with some kind of H symbol. Seems pretty consistent compared to similar searches for obsolete components.

**Comment by KeLaiFu** [comment]
after a quick google, it seems the H branded one was for sale at electrodruid in the past (now sold out and replaced with the AS version).
